- name: "Install MariaDB and dependencies"
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present
    update_cache: yes

- name: "Stop MariaDB to reset root passwd as first login"
  ansible.builtin.systemd:
    name: mariadb
    state: stopped

- name: "Create reset_root_password.sh script"
  ansible.builtin.copy:
    dest: /usr/local/bin/reset_root_password.sh
    content: |
      #!/bin/bash
      mysqld_safe --skip-grant-tables --skip-networking &
      sleep 5
      mysql -u root <<EOF
      FLUSH PRIVILEGES;
      ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mariadb_root_password }}';
      EOF
    mode: '0755'

- name: "Execute reset_root_password.sh script"
  ansible.builtin.command:
    cmd: /usr/local/bin/reset_root_password.sh

- name: "Remove reset_root_password.sh script"
  ansible.builtin.file:
    path: /usr/local/bin/reset_root_password.sh
    state: absent

- name: "Create PowerDNS database"
  community.mysql.mysql_db:
    name: pdns
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: "Grant privileges to PowerDNS user"
  community.mysql.mysql_user:
    name: pdnsadmin
    host: localhost
    password: "{{ pdns_user_password }}"
    priv: "pdns.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"

- name: "Flush privileges"
  ansible.builtin.command:
    cmd: >
      mysql -u root -p{{ mariadb_root_password }} -e "FLUSH PRIVILEGES;"

- name: "Reload service mariadb"
  ansible.builtin.systemd_service:
    state: mariadb
    daemon_reload: true
    name: crond

- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd_service:
    name: mariadb
    enabled: true
    masked: no