- name: "Install PowerDNS with MariaDB backend"
  ansible.builtin.apt:
    name:
      - pdns-server
      - pdns-backend-mysql
    state: "present"

- name: "Configure pdns.conf"
  ansible.builtin.template:
    src: "templates/pdns.conf.j2"
    dest: "/etc/powerdns/pdns.conf"
    mode: '0644'
  notify: "Restart PowerDNS"

- name: "Restart PowerDNS"
  ansible.builtin.service:
    name: "pdns"
    state: "restarted"
