version: "3.8"
services:
  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pdns
      MYSQL_USER: pdnsadmin
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  powerdns:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./powerdns
    container_name: powerdns
    environment:
      PDNS_gmysql_host: mariadb
      PDNS_gmysql_port: 3306
      PDNS_gmysql_user: pdnsadmin
      PDNS_gmysql_password: ${MYSQL_PASSWORD}
      PDNS_gmysql_dbname: pdns
    ports:
      - "1053:53/udp"
      - "1053:53/tcp"
      - "8081:8081"
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
    depends_on:
      - powerdns
    restart: always

volumes:
  mariadb_data:
  nginx_data:
