---
- name: "Ensure system packages are updated"
  ansible.builtin.apt:
    update_cache: true

- name: "Install required system dependencies"
  ansible.builtin.apt:
    name:
      - python3-dev
      - libmysqlclient-dev
      - pkg-config
      - gcc
    state: present

- name: "Install PyMySQL for MySQL interactions"
  ansible.builtin.pip:
    name: pymysql
    state: present
