- name: "Deploy PowerDNS with Docker-in-Docker"
  hosts: localhost
  become: true
  tasks:
    - name: "Start DinD container"
      docker_container:
        name: "dind"
        image: "docker:stable-dind"
        privileged: true
        state: "started"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    - name: "Deploy Docker Compose stack inside DinD"
      copy:
        dest: "/root/docker-compose.yml"
        content: |
          {{ lookup('file', 'docker/docker-compose.yml') }}
      notify: Start DinD Stack

  handlers:
    - name: "Start DinD Stack"
      command: "docker-compose -f /root/docker-compose.yml up -d"
